config/routes.rb
Rails.application.routes.draw do
  resources :posts

  root 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :author, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsVue</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_list.html.erb
<table style="border: 1px solid red">
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.author %></td>
        <td><%= post.content %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/posts/_vue_app.html.erb
<div id="app" style="border: 1px solid blue">
  <table>
    <thead>
      <tr>
        <th>Title</th>
        <th>Author</th>
        <th>Content</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <tr v-for="post in posts">
        <td>{{ post.title }}</td>
        <td>{{ post.author }}</td>
        <td>{{ post.content }}</td>
        <!--
        <td><a href="{{ post.url | pathTo }}">Show</a></td>
        <td><a href="{{ post.url | pathTo 'edit' }}">Edit</a></td>
        -->
        <td><a @click="showPost($index, post.id)">Show</a></td>
        <td><a @click="editPost($index, post.id)">Edit</a></td>
        <td><button v-on:click="removePost($index, post.id)">X</button></td>
      </tr>
    </tbody>
  </table>

  <hr>

  <div class="add-post">
    <form-component :post="newPost" :state="state">
    </form-component>
  </div>
</div>

<template id="formComponent">
  <form class="" id="" action="" onsubmit="return false;">
    <%= hidden_field_tag :authenticity_token %>
    <input v-model="post.title" placeholder="title">
    <input v-model="post.author" placeholder="author">
    <input v-model="post.content" placeholder="content">
    <button @click="cancel" v-if="post.title">Cancel</button>
    <button @click="addPost" v-if="isAddable">Add</button>
    <button @click="updatePost" v-if="isEdit">Update</button>
  </form>
</template>

<script>
Vue.component('form-component', {
  props: ['post', 'state'],
  template: '#formComponent',
  methods: {
    addPost: function () {
      var that = this;
      var title = this.post.title.trim();
      if (title) {

        this.$http.post('/posts.json', { post: that.post })
          .then(
            function success(res) {
              console.info(res);

              that.$dispatch('list-update');

              that.errors = {}
              that.post = {};
            },
            function error(res) {
              that.errors = res.data.errors
            }
          );
      }
    },

    updatePost: function() {
      var that = this;
      console.log('updatePost', this.post);

      if (this.post.id) {
        this.$http.patch('/posts/' + that.post.id + '.json', { post: that.post })
          .then(
            function success(res) {
              console.info(res);

              that.$dispatch('list-update');

              that.errors = {};
              that.post = {};
              that.state = '';
            },
            function error(res) {
              that.errors = res.data.errors
            }
          );
      }
    },

    cancel: function() {
      this.state = '';
      this.post = {};
    }
  },
  computed: {
    isAddable: function() {
      return this.state !== 'show' && this.state !== 'edit';
    },
    isEdit: function() {
      return this.state === 'edit';
    }
  }
});

Vue.filter('pathTo', function (path, action) {
  // return processed value
  if (!path) return;

  var rtn = path.split('.json');

  if(action === 'edit') {
    rtn.push('/edit');
  }

  return rtn.join();
});

/* Set vue-resource */
Vue.use(VueResource);
Vue.http.interceptors.push((request, next) => {
  request.data.authenticity_token = '<%= form_authenticity_token %>';
  // continue to next interceptor
  next();
});

/* Intial Vue App */
new Vue({
  el: '#app',
  data: {
    newPost: {},
    posts: [
      { title: '---' }
    ],
    state: ''
  },
  created: function() {
    this.fetchPosts();
  },
  methods: {
    fetchPosts: function() {
      var that = this;
      this.$http.get('/posts.json')
        .then(
          function success(res) {
            console.info(res);
            console.info('fetch_data: ', res.data);

            that.errors = {}
            that.posts = res.data;
            that.newPost = {};
          },
          function error(res) {
            that.errors = res.data.errors
          }
        )
    },

    showPost: function(index, post_id) {
      this.state = 'show';
      this.newPost = this.posts[index];
      console.log('showPost');
    },

    editPost: function(index, post_id) {
      this.state = 'edit';
      this.newPost = Object.assign({}, this.posts[index])
      console.log('editPost', this.newPost);
    },

    removePost: function (index, post_id) {
      var that = this;

      console.warn('removePost: ', index, post_id);

      if (post_id) {
        this.$http.delete('/posts/' + post_id + '.json', { /* post: { title: title, author: 'ralph', content: content }, */ })
          .then(
            function success(res) {
              console.info(res);
              that.errors = {};
              that.posts.splice(index, 1);
            },
            function error(res) {
              that.errors = res.data.errors
            }
          );
      }
    }
  },
  events: {
    'list-update': function() {
      console.log('list-update');
      this.fetchPosts();
    }
  }
})
</script>

app/views/posts/_vue_form.html.erb
<form class="" id="" action="" onsubmit="return false;">
  <%= hidden_field_tag :authenticity_token %>
  <input v-model="newPost.title" placeholder="title">
  <input v-model="newPost.author" placeholder="author">
  <input v-model="newPost.content" placeholder="content">
  <button @click="cancel" v-if="newPost.title">Cancel</button>
  <button @click="addPost" v-if="isAddable">Add</button>
  <button @click="updatePost" v-if="isEdit">Update</button>
</form>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<%= render 'list' %>
<br>

<%= render 'vue_app' %>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @post.author %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>